source 'https://github.com/CocoaPods/Specs.git'

platform :ios,  '8.0'
use_frameworks!

def pro_pods
	pod 'PieceStore', '~> 4.0.1'
    #pod 'PieceStore', '~> 3.0.2'
end

target 'Example' do
    pro_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end